networks:
  api-network:

volumes:
  db-data:

services:
  db:
    image: postgres:17
    container_name: catechism-management-system-db
    ports:
      - "5432:5432"
    networks:
      - api-network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catechism-management-system
    volumes:
      - db-data:/var/lib/postgresql/data
